[build]
  base = "apps/web"
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://db.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "supabaseKey123abc" 